import { Metadata } from 'next';
import { Providers } from './providers';
import { fonts } from './fonts';
import { VStack, Box } from '@chakra-ui/react';
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Dota2Bro | Team & Players catalog",
  description: "Generated by create next app & Chakra UI and Anastasiia Berest",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={`${fonts.lato.variable}`}>
      <body>
        <Providers>
          <VStack
            flex={1}
            spacing={0}
            alignItems="stretch"
            w="full"
            minH={{ md: '100vh' }}
          >
            <Header />
            <Box as="main" flex={1} w="full" display="flex" flexDir="column">
              {children}
            </Box>
            <Footer />
          </VStack>
        </Providers>
      </body>
    </html>
  );
}
