import type { Metadata } from "next";
import { Providers } from './providers'

import { fonts } from './fonts'
import { VStack, Box } from '@chakra-ui/react'

import Header from "@/components/Header"
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <Providers>
          <VStack
            flex={1}
            spacing={0}
            alignItems="stretch"
            w="full"
            minH={{ md: '100vh' }}
          >
            <Header />
            <Box as="main" flex={1} w="full"> {children}</Box>
            <Footer />
          </VStack>
        </Providers>
      </body>
    </html>
  );
}
