// src/app/metadata.ts
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dota2Bro | Team & Players catalog",
  description: "Generated by create next app & Chakra UI and Anastasiia Berest",
};
